backend:
  name: github
  repo: DaviTeodoro/blog

media_folder: "static/images"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - label: "Featured Image"
        name: "cover"
        widget: "object"
        fields: 
          - {label: "Featured Image", name: "cover", widget: "image"}
          - {label: "Featured Image", name: "cover", widget: "string"}
          - {label: "Featured Image Fullscreen", name: "fullscreen", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}
